# -*- coding: utf-8 -*-
"""Manual Linear Regression Model-Salary_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPgXk089cir6BrQ_qH67e1TGAINbjOfr
"""

import numpy as np
import pandas as pd

data=pd.read_csv("Salary_Data.csv")

data.head()

x=data["YearsExperience"]
y=data["Salary"]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

X=data.iloc[:,0]
Y=data.iloc[:,1]

m=0
c=0
L=0.001
epochs=2000
n=x_train.shape[0]

# Performing Gradient Descent
for i in range(epochs):
    Y_pred = m*X + c  # The current predicted value of Y
    D_m = (-2/n) * sum(X * (Y - Y_pred))  # Derivative wrt m
    D_c = (-2/n) * sum(Y- Y_pred)  # Derivative wrt c
    m = m - L * D_m  # Update m
    c = c - L * D_c  # Update c

print (m, c)

x=float(input("Enter Experience"))

result=m*x+c
print(result)