# -*- coding: utf-8 -*-
"""Multiple Linear Regression-age experience salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yqkUy4avtZS_S1MHRbu4Hs4aRSlMe6L9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("age-experience-Salary.csv")

data.head(10)

sns.heatmap(data.corr(),annot=True)

x=data.drop(["income"],axis=1)

y=data["income"]

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
print("Training Accuracy: ",lr.score(x_train,y_train))
print("Testing Accuracy: ",lr.score(x_test,y_test))

lr.intercept_

lr.coef_

l=[]
x=float(input("Enter Age"))
y=float(input("Enter Experience"))
l.append(x)
l.append(y)

y_prediction=lr.predict([l])
print("Income According to My Model: ",y_prediction)

